AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Max: 130

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 12

Metrics/LineLength:
  Max: 130

Metrics/AbcSize:
  Max: 35

Metrics/MethodLength:
  Max: 30

Security/Eval:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

