
Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 101

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 35

Metrics/MethodLength:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 11


Security/Eval:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

